export enum PaymentStatus {
  CAPTURED = 'Captured',
  COMPLETED = 'Completed',
  CREATED = 'Created',
  FAILED = 'Failed',
  SETTLED = 'Settled',
}

export enum ResponseStatus {
  OK = 200,
  CREATED = 201,
  APPROVAL_PENDING = 202,
  CONNECTIVITY_ERROR = 0,
  ACCESS_DENIED_401 = 401,
  ACCESS_DENIED_403 = 403,
  BAD_REQUEST = 400,
}

/**
 * Payee group error types enumeration
 */
export enum AccountGroupRequestErrorType {
  ACCESS_DENIED = 'ACCESS_DENIED',
  CONNECTIVITY_ERROR = 'CONNECTIVITY_ERROR',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  ALREADY_IN_PENDING_STATE = 'ALREADY_IN_PENDING_STATE',
  E_ALREADY_EXISTS = 'E_ALREADY_EXISTS',
  E_NOT_EXISTS = 'E_NOT_EXISTS',
  E_INVALID_DATA_GROUP_ITEMS = 'E_INVALID_DATA_GROUP_ITEMS',
  E_INVALID_DATA_GROUP_TYPE = 'E_INVALID_DATA_GROUP_TYPE',
  E_INVALID_SERVICE_AGREEMENT = 'E_INVALID_SERVICE_AGREEMENT',
}
